config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/admin' do
    resources :users do
      get 'update_status', on: :member
    end
  end

  root "autos#index"

  resources :roles
  resources :autos
  resources :cars
  resources :comments
  resources :replies

end

app/models/auto.rb
class Auto < ApplicationRecord
  has_many :cars, dependent: :destroy

  validates :brand, presence: true
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: %i[ show edit update destroy ]

  def index
    @autos = Auto.all.order(:brand)
  end

  def show
  end

  def new
    @auto = Auto.new
  end

  def edit
  end

  def create
    @auto = Auto.new(auto_params)
    if @auto.save
      redirect_to autos_path, notice: 'Auto was successfully created.'
    else
      flash.now[:alert] = 'Auto was not successfully created!'
      render :new
    end
  end

  def update
    if @auto.update(auto_params)
      redirect_to autos_path, notice: 'Auto was successfully updated.'
    else
      redirect_to autos_path, alert: 'Auto was not successfully updated.'
    end
  end

  def destroy
    @auto.destroy

    respond_to do |format|
      format.html { redirect_to autos_url, notice: "Auto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_auto
      @auto = Auto.find(params[:id])
    end

    def auto_params
      params.require(:auto).permit(:brand)
    end
end

app/helpers/autos_helper.rb
module AutosHelper
  
end

app/views/autos/_auto.html.slim
div class="button_box"  
  = link_to "#{auto.brand}", cars_path(auto_id: auto.id), class:"btn btn-outline-dark"
  - if can? :update, auto
    a.btn.btn-light.btn-sm href=edit_auto_path(id: auto.id)
      svg.bi.bi-pencil-fill[xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewbox="0 0 16 16"]
        path[d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"]

app/views/autos/_form.html.slim
= form_with(model: @auto) do |form|
  - if @auto.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@auto.errors.count, "error")} prohibited this audi from being saved:"
      ul
        - @auto.errors.each do |error|
          li = error.full_message

  .container
    .mb-3
      = form.label :brand, style: "color: white"
      = form.text_field :brand, class: "form-control"
    
    = link_to "Back to auto", :back, class: "btn btn-secondary"
    = form.submit class:"btn btn-outline-success"

app/views/autos/edit.html.slim
.container
  h1 style="color: white" Editing auto
  div class="button_box" style="display: flex;"
    == render "form", auto: @auto

app/views/autos/index.html.slim
.container
  .row
    h1 style="color: white" Auto
    - if can? :create, @auto
      = link_to "New auto", new_auto_path, class:"btn gradient_knopka col-md-2 offset-md-10"
  #autos
  .card
    strong Brands: 
    - @autos.each do |auto|
      == render auto
    
  

app/views/autos/new.html.slim
.container
  h1 style="color: white" New auto
  div class="button_box" style="display: flex;"
    == render "form", auto: @auto

app/views/autos/show.html.slim
.card style="width: 900px"
  div
    strong Brand: 
    = @auto.brand

.container.col-md-5.offset-md-6
  div class="button_box" style="display: flex;"

    = button_to "Destroy this auto", auto_path(@auto), data: { turbo_method: :delete }, method: :delete, class: "btn btn-danger"

    => link_to "Edit this auto", edit_auto_path(@auto),class: "btn btn-outline-warning"

    =< link_to "Back to all auto", autos_path, class: "btn btn-secondary"