config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/admin' do
    resources :users do
      get 'update_status', on: :member
    end
  end

  root "autos#index"

  resources :roles
  resources :autos
  resources :cars
  resources :comments
  resources :replies

end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :restrict_with_exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  load_and_authorize_resource

  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
    if @role.users.empty?
      @associated_user = 'None'
    else
      @associated_users = @role.users.map(&:user_name).join(', ')
    end
  end

  # GET /roles/new
  def new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:role_name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.slim
= form_with(model: @role) do |form|
  - if @role.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      ul
        - @role.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.label :description, style: "display: block"
    = form.text_field :description

  div
    = form.submit

app/views/roles/_role.html.slim
div id="#{dom_id role}"
  p
    strong Name:
    =< role.role_name
  p
    strong Description:
    =< role.description

app/views/roles/edit.html.slim
h1 Editing role

== render "form", role: @role

br

div
  => link_to "Show this role", @role
  '|
  =< link_to "Back to roles", roles_path

app/views/roles/index.html.slim
h1 Roles

#roles
  - @roles.each do |role|
    == render role
    p
      = link_to "Show this role", role

= link_to "New role", new_role_path

app/views/roles/new.html.slim
h1 New role

== render "form", role: @role

br

div
  = link_to "Back to roles", roles_path

app/views/roles/show.html.slim
== render @role
p
  strong
    | Associated users:
  = @associated_users

div
  => link_to "Edit this role", edit_role_path(@role)
  '|
  =< link_to "Back to roles", roles_path

  = button_to "Destroy this role", @role, data: { turbo_method: :delete }