config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '/admin' do
    resources :users do
      get 'update_status', on: :member
    end
  end

  root "autos#index"

  resources :roles
  resources :autos
  resources :cars
  resources :comments
  resources :replies

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :auto
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_rich_text :description

  validates :model, presence: true
  validates :year, presence: true
  validates :color, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :colors, only: %i[ show new edit update destroy ]

  load_and_authorize_resource
  # GET /cars or /cars.json
  def index
    if params[:auto_id].present?
      @cars = Auto.find_by(id: params[:auto_id]).cars
    else
      @cars = Car.all
    end
  end

  # GET /cars/1 or /cars/1.json
  def show
    find_replies_for_comment

    @comments = Comment.where(car_id: @car.id).order(id: :desc)
  end

  # GET /cars/new
  def new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car.user_id = current_user.id
      if @car.save
        redirect_to cars_path, notice: 'Car was successfully created.'
      else
        flash.now[:alert] = 'Car was not successfully created!'
        render :new
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    if @car.update(car_params)
      redirect_to cars_path, notice: 'Car was successfully updated.'
    else
      redirect_to cars_path, alert: 'Car was not successfully updated.'
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    if @car.destroy
      redirect_to cars_path, notice: 'Car was successfully destroyed.'
    else
      redirect_to cars_path, alert: 'Car was not successfully destroyed.'
    end
  end
 
  def colors
    @colors = ["Black", "White", "Silver", "Gray", "Red", "Blue", "Green", "Gold", "Brown", "Orange", "Yellow", "Purple"]
  end

  private

    # Use callbacks to share common setup or constraints between actions.
   

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:model, :year, :color, :price, :description, :auto_id, :user_id)
    end

    def find_replies_for_comment
      @car = Car.find(params[:id])
      @comments = Comment.where(car_id: @car.id).order(id: :desc)
      @replies = []

      @comments.each do |comment|
        @replies += Reply.where(comment_id: comment.id)
      end
    end    
end

app/helpers/cars_helper.rb
module CarsHelper
  
end

app/views/cars/_car.html.slim
div class="button_box"
h5 style="color: red"
    - if car.user.status == "unblocked"
        = car.auto.brand
        = link_to "#{car.model}", car, class:"btn btn-outline-dark"

app/views/cars/_form.html.slim
= form_with(model: @car) do |form|
  - if @car.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      ul
        - @car.errors.each do |error|
          li = error.full_message
  .container style="width: 750px"

    .mb-3
      = form.label :model, style: ("color: white")
      = form.text_field :model, class: "form-control", style: ("text-align:center")

    .mb-3
      = form.label :year, style: "color: white"
      = form.select :year, (1960..2023).to_a, { prompt: "Select year ..." }, class: "form-control", style: ("text-align:center")

    .mb-3
      = form.label :color, style: "color: white"
      = form.select :color, options_for_select(@colors), { prompt: "Select color ..." }, class: "form-control", style: ("text-align:center")

    .mb-3
      = form.label :price, style: "color: white"
      = form.number_field :price, class: "form-control", style: ("text-align:center")

    .mb-3
      = form.label :description, style: "color: white"
      = form.rich_text_area :description, class: "form-control", style: "text-align:center"

    .mb-3 
      = form.label :auto, style: "color: white"
      = form.collection_select(:auto_id, Auto.all.order(:brand), :id, :brand, {prompt: "Select auto ..."}, {class: "form-control", style: "text-align:center"})

    .container.col-md-7.offset-md-8
      div class="button_box" style="display: flex;"
        = link_to "Back to cars", cars_path, class: "btn btn-secondary"
        = form.submit class:"btn btn-outline-success"

app/views/cars/edit.html.slim
.container
  h1 style="color: white" Editing car

  == render "form", car: @car

app/views/cars/index.html.slim
.container
  .row
    h1 style="color: white" Cars
    - if can? :create, Car
      - if current_user.status == "unblocked"
        = link_to "New car", new_car_path, class:"btn gradient_knopka col-md-2 offset-md-10"

  .card
    - @cars.each do |car|
      == render car
        
    

app/views/cars/new.html.slim
.container
  h1 style="color: white" New car

  == render "form", car: @car

br

app/views/cars/show.html.slim
p style="color: green" = notice

.card style="width: 800px"
  strong 
    =< link_to "#{@car.auto.brand}", cars_path(auto_id: @car.auto_id), class:"btn btn-outline-dark", style: "font-size: 30px"
  p
    strong Model:
    =< @car.model
  p
    strong Year:
    =< @car.year
  p
    strong Color:
    =< @car.color
  p
    strong Price:
    =< @car.price
  p
    strong Seller:
    = link_to "#{@car.user.user_name}", @car.user, class: "btn", style: "color: blue"
  p
    strong Description:
    =< @car.description

  .container.col-md-5.offset-md-8 
    div.button_box style="display: flex; justify-content: flex-end; margin-bottom: 1px"
      - if can? :destroy, @car
        = button_to "Destroy", car_path(@car), method: :delete, class: "btn btn-danger",  style: "height: 40px"
      - if can? :edit, @car
        =< link_to "Edit", edit_car_path, class: "btn btn-warning", style: "height: 40px"
        
      => link_to "Back", :back, class: "btn btn-secondary", style: "height: 40px; margin-right: 65px;"

.card style="width: 800px"
  p class="comment_word"
    | Comments
  - if current_user.status == "unblocked" 
    = form_for(Comment.new) do |f|
      .input-group
        = f.text_area :content, placeholder: 'Write a comment...', class: "form-control"
        .input-group-append
          = button_tag(type: 'submit', class: 'btn btn-light', style: 'margin-left: 10px; background-color: #f8f4f4') do
            svg[xmlns="http://www.w3.org/2000/svg" width="16" height="50" fill="currentColor" color="blue" class="bi bi-send-fill" viewBox="0 0 16 16"]
              path[d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z"]
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :car_id, value: @car.id
  - else
    p style="text-align: center; color: red"
      |You can't leave comments
  - if @comments.present?
    - @comments.each do |comment|
      = render partial: 'comments/comment', locals: { comment: comment }
  - else
    |No comments
    